// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOBHK0XGrPZXTfJYEldoHlKzbrDV4hAaQ',
    appId: '1:234427220108:web:ad73e56747029b8dfd3ba9',
    messagingSenderId: '234427220108',
    projectId: 'hotel-kitchen-management-a352b',
    authDomain: 'hotel-kitchen-management-a352b.firebaseapp.com',
    storageBucket: 'hotel-kitchen-management-a352b.appspot.com',
    measurementId: 'G-R52E4ZLXG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAemlFPTftthvD9F12iFSBj37pEeqqxHA',
    appId: '1:234427220108:android:4e0b907e79a738dcfd3ba9',
    messagingSenderId: '234427220108',
    projectId: 'hotel-kitchen-management-a352b',
    storageBucket: 'hotel-kitchen-management-a352b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwlHl7x2rkbe-ewTvozMIZaCMwhF031k',
    appId: '1:234427220108:ios:6bff194a675d0849fd3ba9',
    messagingSenderId: '234427220108',
    projectId: 'hotel-kitchen-management-a352b',
    storageBucket: 'hotel-kitchen-management-a352b.appspot.com',
    iosBundleId: 'com.example.hotelKitchenManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwlHl7x2rkbe-ewTvozMIZaCMwhF031k',
    appId: '1:234427220108:ios:20ff63c4909e2547fd3ba9',
    messagingSenderId: '234427220108',
    projectId: 'hotel-kitchen-management-a352b',
    storageBucket: 'hotel-kitchen-management-a352b.appspot.com',
    iosBundleId: 'com.example.hotelKitchenManagement.RunnerTests',
  );
}
